# Generated by Django 6.0.4 on 2026-04-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('medical_record_number', models.CharField(blank=True, help_text='Optional clinic-specific patient identifier.', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icd_code', models.CharField(blank=True, help_text='Optional ICD or similar coding system identifier.', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', max_length=16)),
                ('diagnosed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_diagnoses', to='api.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-diagnosed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(help_text='Dosage, schedule, lifestyle recommendation, or other instructions.')),
                ('issued_at', models.DateTimeField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='api.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.patientprofile')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_written', to='api.doctorprofile')),
            ],
            options={
                'ordering': ['-issued_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['patient', '-diagnosed_at'], name='api_diagnos_patient_228b46_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['recorded_by', '-diagnosed_at'], name='api_diagnos_recorde_41ac53_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-issued_at'], name='api_prescri_patient_84d3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by', '-issued_at'], name='api_prescri_prescri_2ae8af_idx'),
        ),
    ]
