# Generated by Django 6.0.4 on 2026-04-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=16)),
                ('reason', models.TextField(blank=True, help_text='Optional description of symptoms or the reason for the visit.')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.patientprofile')),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
                'indexes': [models.Index(fields=['doctor', 'starts_at'], name='api_appoint_doctor__3bbfde_idx'), models.Index(fields=['patient', 'starts_at'], name='api_appoint_patient_a037eb_idx'), models.Index(fields=['status', 'starts_at'], name='api_appoint_status_daf147_idx')],
            },
        ),
    ]
