# Generated by Django 6.0.4 on 2026-04-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=16)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_as_doctor', to='api.doctorprofile')),
                ('recipient_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_as_patient', to='api.patientprofile')),
                ('sender_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_as_doctor', to='api.doctorprofile')),
                ('sender_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_as_patient', to='api.patientprofile')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['sender_patient', 'recipient_doctor', '-created_at'], name='api_message_sender__b6f698_idx'), models.Index(fields=['sender_doctor', 'recipient_patient', '-created_at'], name='api_message_sender__d91f40_idx')],
            },
        ),
    ]
